### ISSUE TITLE
Result destructuring error (Cannot read property 'Symbol(Symbol.iterator)' of undefined)

### ISSUE THREAD

**Issue by vhf** [einarjegorov/graphile-upsert-plugin#5]
I spent some time finding out why I was getting `TypeError: Cannot read property 'Symbol(Symbol.iterator)' of undefined` with the following mutation:

```gql
mutation ($headline: String!, $threadType: ThreadType!, $status: Status!) {
  upsertThread (input: {
    thread: {
      headline: $headline,
      threadType: $threadType,
      status: $status
    }
  }) {
    thread {
      id
    }
  }
}
```

As it turns out, `await viaTemporaryTable` for this mutation returns something like: `[{ id: 12 }]`, and the above error message was caused by trying to destructure that like this:

```
> const {rows: [row]} = [{id: 12}]
TypeError: Cannot read property 'Symbol(Symbol.iterator)' of undefined
```

Here is how I patched graphile-upsert-plugin locally to get everything to work:

```diff
-   const { rows: [row] } = await viaTemporaryTable(
+   const result = await viaTemporaryTable(
      pgClient,
      sql.identifier(table.namespace.name, table.name),
      mutationQuery,
      insertedRowAlias,
      query
    );

    return {
      clientMutationId: input.clientMutationId,
-     data: row,
+     data: result[0],
    };
```

---
Using:

- `postgraphile@4.0.1`
- `graphql@0.13.2`

**Comment by benjie** [comment]
Confirmed: `const { rows: [row] } = await viaTemporaryTable(` is not valid syntax with `viaTemporaryTable` (not sure if it was at some point during alpha/beta, but it's not since at least the v4.0.0 release).
