### ISSUE TITLE
That is this ?

### ISSUE THREAD

**Issue by OLDIN** [einarjegorov/graphile-upsert-plugin#6]
**That is this ?**
![image](https://user-images.githubusercontent.com/15104330/49697166-b42be880-fbbc-11e8-8b5b-584007c98346.png)

This can be combined into one filter method.

**Comment by cdaringe** [comment]
I'd put $5 down that turbofan already optimizes these out.  respectfully, this is a pretty pedantic and non-value-add issue.

**Comment by benjie** [comment]
Presumably it's during a part of the code that's not performance critical (e.g. schema generation), where ease of reading the code is more important than the performance of the code.

If you desire to submit performance fixes then it would be preferable to do so with a pull request containing the code changes, and some benchmarks showing the gains. Tip: keep pull requests small and focussed, don't change code formatting or organisation in unrelated places.

**Comment by outdoteth** [comment]
🤣
